services:
  - type: web
    name: my-hairstyles-1
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: FRONTEND
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
